package:
  name: cloudflared
  version: 2023.5.1
  epoch: 5
  description: Cloudflare Tunnel client
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - ca-certificates-bundle
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cloudflare/cloudflared
      tag: ${{package.version}}
      expected-commit: 867360c8dd3dd5d88cfbcfcb7ad9b587a04ab82d

  - uses: go/build
    with:
      go-package: go-1.20 # pin to a specific version of Go as not working with go-1.21 yet
      packages: ./cmd/cloudflared
      output: cloudflared
      ldflags: -s -w -extldflags=-static -X "main.Version=${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: cloudflare/cloudflared
    strip-prefix: 2023. # only auto update within the year